<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20

        Button:
            text: "Hello World!" 

        Button:
            text: "Goodbye World!" 

        Button:
            text: "I'm hungry!"
            #pos_hint: {'center_x': 0.5} 
            #size_hint:(None,None)
            #width: 100
            #height: 50

       
