#!/bin/sh
'''exec' C:/Users/maxik/Documents/Semester_6/Projektarbeit/github_repo/Steganography/stego-env_local/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from send2trash.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
